# Generated by Django 5.0 on 2023-12-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_loan_actual_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='actual_installments',
        ),
    ]
