# Generated by Django 5.0 on 2023-12-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_loan_paid_loan_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_date',
        ),
    ]
