# Generated by Django 5.0 on 2023-12-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_installment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Installment',
            new_name='Parcelas',
        ),
    ]
