# Generated by Django 5.0 on 2023-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_rename_installment_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelas',
            name='amount_per_installment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
