# Generated by Django 5.0 on 2023-12-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_parcelas_amount_per_installment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelas',
            old_name='loan',
            new_name='owner',
        ),
    ]
