# Generated by Django 5.0 on 2023-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_rename_loan_parcelas_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
