# Generated by Django 5.0 on 2023-12-26 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_loan_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelas',
            name='installment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
