# Generated by Django 5.0 on 2023-12-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_loan_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelas',
            name='amount',
        ),
    ]
