# Generated by Django 5.0 on 2023-12-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_remove_parcelas_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelas',
            name='owner_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
    ]
